FROM nginx:alpine

# nginxの設定ファイルをコピー
COPY nginx.conf /etc/nginx/conf.d/default.conf

# フロントエンドのファイルをコピー
COPY frontend /usr/share/nginx/html/frontend

# ポートを公開
EXPOSE 80

# nginxを起動
CMD ["nginx", "-g", "daemon off;"]
